name: Release

on:
  push:
    tags:
      - 'v*'  # Only run on version tags (e.g., v1.0.0)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Build the application
        run: |
          # Command to build your application (e.g., using PyInstaller)

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: path/to/your/installer.exe  # Replace with the path to your .exe installer
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
