name: Build and Release Installer

on:
  push:
    tags:
      - 'v*'  # This workflow will run when a tag is pushed (e.g., v1.0.0)

jobs:
  build_installer:
    runs-on: windows-latest  # Use a Windows runner to build the installer

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up Inno Setup
      uses: dmulholland/inno-setup-action@v1
      with:
        version: "5.6.1"  # Specify the version of Inno Setup to use

    - name: Build the Installer
      run: |
        iscc "C:\Users\newto\OneDrive\Documents\GitHub\CCFL-Application\Data\Inno"  # Path to your Inno Setup script
        echo "Installer built successfully."

    - name: Upload Installer as Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          C:\Users\newto\OneDrive\Documents\GitHub\CCFL-Application\Releases\Latest\CCFL Setup.exe  # Path to the generated .exe file
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
